openapi: 3.0.3
info:
  title: Shorty API
  description: Спецификация API сервиса
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authorized user request
    adminAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Auth with admin role

paths:
  /api/v1/links:
    get:
      summary: Получение всех ссылок пользователя
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uid:
                      type: string
                    title:
                      type: string
                    subdomain:
                      type: string
                    domainUid:
                      type: string
                    password:
                      type: string
                    url:
                      type: string
                    changeDt:
                      type: string
                    updateDt:
                      type: string
        '403':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера
      security:
        - bearerAuth: []
    post:
      summary: Добавление ссылки к пользователю
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domainUid:
                  type: string
                title:
                  type: string
                subdomain:
                  type: string
                url:
                  type: string
                password:
                  type: string
              required:
                - domainUid
                - title
                - subdomain
                - url
                - password
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  title:
                    type: string
                  subdomain:
                    type: string
                  domainUid:
                    type: string
                  password:
                    type: string
                  url:
                    type: string
                  changeDt:
                    type: string
                  updateDt:
                    type: string
        '403':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера
      security:
        - bearerAuth: [ ]
  /api/v1/links/{uid}:
    get:
      summary: Получение ссылки пользователя
      parameters:
        - name: uid
          in: path
          description: Идентификатор ссылки
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  title:
                    type: string
                  subdomain:
                    type: string
                  domainUid:
                    type: string
                  password:
                    type: string
                  url:
                    type: string
                  changeDt:
                    type: string
                  updateDt:
                    type: string
        '403':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера
      security:
        - bearerAuth: [ ]
    delete:
      summary: Удаление ссылки пользователя
      parameters:
        - name: uid
          in: path
          description: Идентификатор ссылки
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  title:
                    type: string
                  subdomain:
                    type: string
                  domainUid:
                    type: string
                  password:
                    type: string
                  url:
                    type: string
                  changeDt:
                    type: string
                  updateDt:
                    type: string
        '403':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера
      security:
        - bearerAuth: [ ]
    put:
      summary: Изменение ссылки пользователя
      parameters:
        - name: uid
          in: path
          description: Идентификатор ссылки
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  title:
                    type: string
                  subdomain:
                    type: string
                  domainUid:
                    type: string
                  password:
                    type: string
                  url:
                    type: string
                  changeDt:
                    type: string
                  updateDt:
                    type: string
        '403':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера
      security:
        - bearerAuth: [ ]
  /api/v1/domains:
    get:
      summary: Получение доменов
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    value:
                      type: string
        '403':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера
      security:
        - bearerAuth: [ ]
    post:
      summary: Создание нового домена
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    value:
                      type: string
        '403':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера
      security:
        - adminAuth: [ ]
