services:
  main-app:
    container_name: ShortyApp
    build: ./main-app
    environment:
      KEYCLOAK_BASE_URL: http://172.16.2.9:8180
      KEYCLOAK_CLIENT_ID: shorty-client
      KEYCLOAK_CLIENT_SECRET: 4pNtsFCKScTRhHGOlKaIVgHA9gCI9MFz
      KEYCLOAK_REALM: shorty
      AUTH_SECRET: SGVsbG8sIHdvcmxkIQ==
      BACKEND_URL: http://172.16.2.9:2001/api/v1
      PORT: 3000
    ports:
      - "3000:3000"
  redirect-app:
    container_name: ShortyRedirectApp
    build: ./redirect-app
    environment:
      BACKEND_URL: http://172.16.2.9:2001/api/v1
      PORT: 3001
      DOMAIN: localhost:3001
    ports:
      - "3001:3001"
