name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-main-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Set up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install package dependencies for main-app
        run: npm install
        working-directory: main-app

      - name: Check linting for main-app
        run: npm run lint
        working-directory: main-app

      - name: Build React app for main-app
        run: npm run build
        working-directory: main-app

  build-redirect-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Set up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install package dependencies for redirect-app
        run: npm install
        working-directory: redirect-app

      - name: Check linting for redirect-app
        run: npm run lint
        working-directory: redirect-app

      - name: Build React app for redirect-app
        run: npm run build
        working-directory: redirect-app
